<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>DContre.MyFinance.CurrencyService.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DContre.MyFinance.DataAccess" Version="1.0.0" />
    <PackageReference Include="DContre.MyFinance.StUtilities" Version="1.0.0" />
    <PackageReference Include="DContre.MyFinance.WebApiBaseConsumer" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.9" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
